[package]
name = "rust_server"
version = "0.1.0"
authors = ["kir4ik <vlados.linkoln@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.15.2"
rust-ini = "0.15"
